### ISSUE TITLE
Figure 5 in paper does not appear to show the SFT+KTO result

### ISSUE THREAD

**Issue by edbeeching** [ContextualAI/HALOs#1]
The fifth column of figure 5 appears to be a repeat of the third column, would it be possible to update the figure?

Also in equation 7 you write \pi^* but I think you meant to write \pi^\theta ?

**Comment by kawine** [comment]
Good catch! Will update the Figure shortly. Also correct about typo in Eq 7.

**Comment by kawin-contextual-ai** [comment]
now fixed, thanks!
