### ISSUE TITLE
Error fix for evaluation script `eval.py`

### ISSUE THREAD

**Issue by yunjae-won** [ContextualAI/HALOs#11]
Thank you for maintaining such an important repository. While using your repository, I was faced with some issues using the `eval.py`, and wanted to check if the following changes required are indeed valid.

1. In line 86 of eval.py, we need to modify `reference_model.resize_token_embeddings(len(tokenizer))` into the following:
```python
if config.loss.name == 'ppo':
    reference_model.resize_token_embeddings(len(tokenizer))
```
this is because we have resized the token embeddings for the reference model only if the loss was ppo (refer to line 170 of `train.py`)

2. When we use the `eval` mode of `eval.py`, we need to change the trainer type from `BasicTrainer` to `DPOTrainer`, otherwise we are faced with the `NotImplementedError` while calling the `get_batch_metrics` method.

Once again, thank you for maintaining an amazing repository which is very easy to use. Thank you so much!

**Comment by kawine** [comment]
Thanks for pointing this out @YJWon99 ! I've pushed the changes that you recommended. Let me know if you have any other issues!
