### ISSUE TITLE
Can you provide a clear description of the dataset structure we can use for our custom dataset. 

### ISSUE THREAD

**Issue by sankydesai** [ContextualAI/HALOs#12]
Something like this?

From the Huggingface DPOTrainer docs:

dpo_dataset_dict = {
    "prompt": [
        "hello",
        "how are you",
        "What is your name?",
        "What is your name?",
        "Which is the best programming language?",
        "Which is the best programming language?",
        "Which is the best programming language?",
    ],
    "chosen": [
        "hi nice to meet you",
        "I am fine",
        "My name is Mary",
        "My name is Mary",
        "Python",
        "Python",
        "Java",
    ],
    "rejected": [
        "leave me alone",
        "I am not fine",
        "Whats it to you?",
        "I dont have a name",
        "Javascript",
        "C++",
        "C++",
    ],
}

**Comment by kawine** [comment]
Unlike with DPO, you don't need to have even numbers of chosen and rejected examples. So it could be something of the form 

dpo_dataset_dict = {
"prompt": [
"hello",
"how are you",
"What is your name?",
"What is your name?",
"Which is the best programming language?",
"Which is the best programming language?",
"Which is the best programming language?",
],
"completion": [
"hi nice to meet you",
"I am fine",
"My name is Mary",
"I dont have a name",
"Javascript",
"C++",
"C++",
],
"type": [
"chosen",
"chosen",
"chosen",
"rejected",
"rejected",
"rejected",
"rejected",
],
}

**Comment by kawine** [comment]
You would then write a get_custom_dataset function in dataloader.py that returns a Dataset object consisting of Example objects (one example per prompt). If your feedback is unary (thumbs up/down), then populate the Example.desirable field. If your feedback is preferences, then populate the Example.pairs field (or both if you have mixed feedback).

Then subclass UnpairedPreferenceDataLoader to write a Dataloader that will return batches of tokenized examples in the order you want.
