### ISSUE TITLE
In dataloder

### ISSUE THREAD

**Issue by patronum08** [ContextualAI/HALOs#2]
https://github.com/ContextualAI/HALOs/blob/8d8aac208e20965d8f3212a2633fab86f15861ff/dataloader.py#L42

In this line, does "i > j" mean "score(i) > score(j)"? I'm a bit confused, thank you for your clarification!
![image](https://github.com/ContextualAI/HALOs/assets/24070800/9ddb1401-eec7-4b58-88ee-7fc8e18eafad)

**Comment by kawin-contextual-ai** [comment]
In datasets where the score is available (e.g., Stanford SHP), that is the right interpretation. In datasets where there is no score (e.g., Anthropic HH), it just means that i is preferred to j in the dataset.
