### ISSUE TITLE
Process oasst dataset

### ISSUE THREAD

**Issue by shuoYan97** [ContextualAI/HALOs#23]
When loading the oasst dataset with the provided function get_oasst() directly, the error occurs: TypeError: Expected a pyarrow.Table or a datasets.table.Table object, but got OASST. Do I miss something to correctly process the data? Thanks
https://github.com/ContextualAI/HALOs/blob/main/dataloader.py#L315

**Comment by shuoYan97** [comment]
Sry I did not see the class Dataset in dataloader.py

**Comment by kawine** [comment]
glad it worked out!
