### ISSUE TITLE
No checkpoint for archangel_sft-dpo_llama7b

### ISSUE THREAD

**Issue by nlee-208** [ContextualAI/HALOs#3]
No available checkpoint for `archangel_sft-dpo_llama7b`

https://huggingface.co/ContextualAI/archangel_sft-dpo_llama7b

**Comment by kawin-contextual-ai** [comment]
Thanks for catching this! We will upload it shortly.

**Comment by xwinxu** [comment]
Thanks for your patience, and apologies, it should be uploaded now!
