### ISSUE TITLE
How to sample from HF models? 

### ISSUE THREAD

**Issue by likenneth** [ContextualAI/HALOs#7]
Hi, this is great great project!

I'm thinking about reproducing your scores in the paper first. Specifically from the model `ContextualAI/archangel_sft_llama7b`. How to sample from this HF model? Right now the eval.py takes in a path from /data/..., which exists only if I trained it myself.

**Comment by kawine** [comment]
You should be able to sample from it as if it were any Llama-7B based Huggingface model: https://huggingface.co/blog/how-to-generate

**Comment by likenneth** [comment]
I was trying to find an easy way to plug HF models into your code base, just for evaluation. 

I've solved my problem. Thank you.

**Comment by likenneth** [comment]
close
