### ISSUE TITLE
How to setup the Environment without Conda?

### ISSUE THREAD

**Issue by dardodel** [ContextualAI/HALOs#8]
What if I don't have access to Conda (Anaconda, Miniconda)? Is there any other way to setup the environment?

**Comment by kawine** [comment]
Can you install packages via pip @dardodel ?

**Comment by dardodel** [comment]
I can pip install python packages. But my cuda version is 11.x and I don't have permission to install 12.x on our servers. Do you think that would be a problem?

**Comment by kawine** [comment]
@dardodel sorry for the late follow up to this. if you can pip install python packages, I would try the following

```
conda create -n halos3 python=3.10.12
pip3 install numpy==1.24.3 ninja==1.11.1.1 packaging==23.1 
conda install pytorch==2.1.1 pytorch-cuda=12.1 -c pytorch -c nvidia
pip3 install flash-attn==2.3.3 
pip3 install transformers==4.35.2 datasets hydra-core==1.3.2 wandb==0.15.3 openai==1.6.1 accelerate==0.21.0 tensor-parallel
```

if you can't use cuda 12.1, i would replace the third line above with 

```
conda install pytorch==2.1.1 pytorch-cuda=11.8 -c pytorch -c nvidia
```

i think this should work, but you may have to change the version of flash-attention in case there are any compatibility issues
